### PR TITLE
issue#106 Support of underlying connection/transactions/commands

### PR DESCRIPTION
**Pull request by pmunin**
https://github.com/borisdj/EFCore.BulkExtensions/issues/106

### CODE REVIEW

**Comment by pmunin** [comment]
@borisdj 
> EFCoreBulkUnderlyingTest is throwing
> System.InvalidCastException : Unable to cast object of type 'EFCore.BulkExtensions.Tests.MyConnection' to type 'System.Data.SqlClient.SqlConnection'.

I fixed something in test, however I never received the casting exception - I only had null reference, because of something missing in test. Please try again and if you still have that exception can you provide a call stack?

**Comment by borisdj** [comment]
I took the new Test and only difference I made is in ConnectionString changed the name of Server from '.\\SQLEXPRESS' to 'localhost'. I am using Sql Server 2017 Developer Edition.

> Result StackTrace:	
at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.ClearPool()
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
   at EFCore.BulkExtensions.Tests.TestContext..ctor(DbContextOptions options) in D:\ProjectsPriv\EFCore.BulkExtensionsUnderConn\EFCore.BulkExtensions.Tests\TestContext.cs:line 37
   at EFCore.BulkExtensions.Tests.EFCoreBulkUnderlyingTest.RunDelete(Boolean isBulkOperation) in D:\ProjectsPriv\EFCore.BulkExtensionsUnderConn\EFCore.BulkExtensions.Tests\EFCoreBulkUnderlyingTest.cs:line 281
   at EFCore.BulkExtensions.Tests.EFCoreBulkUnderlyingTest.OperationsTest(Boolean isBulkOperation) in D:\ProjectsPriv\EFCore.BulkExtensionsUnderConn\EFCore.BulkExtensions.Tests\EFCoreBulkUnderlyingTest.cs:line 29
Result Message:	System.InvalidCastException : Unable to cast object of type 'EFCore.BulkExtensions.Tests.MyConnection' to type 'System.Data.SqlClient.SqlConnection'.

**Comment by borisdj** [comment]
Actually I just got it to work, not sure what was the cause.
I have copied the code again since previously I have made some code cleanup.
I will merge it soon.

**Comment by pmunin** [comment]
hi @borisdj, do you have roughly any expected ETA of merging this?

**Pull request merged**
