### PR TITLE
BatchUpdate - Support Advanced BatchUpdate Queries

### PR DESCRIPTION
**Pull request by RyanThomas73**
**AdvancedBatchUpdate**
* Reworked the `BatchUpdate(Async)` logic to support advanced update queries (e.g. setting properties using inner queries generated via navigation property references).
* Added automated test cases to verify the advanced `BatchUpdate` queries behave as expected.

### CODE REVIEW

**Comment by RyanThomas73** [comment]
@borisdj Could you provide an ETA on when you'll be able to review and accept this PR?

**Comment by borisdj** [comment]
I have merged some previous PullRequest, so could you first resolve current conflicts, then I will merge this also.
Thx for contrib.

**Comment by RyanThomas73** [comment]
@borisdj I pushed an update containing the merge conflict resolution. Thanks much!

**Comment by borisdj** [comment]
Merged 👍

**Pull request merged**
