### PR TITLE
Make owned types (in same table) work in PostgreSQL.

### LINKED ISSUE #795: PostgreSQL BulkInsertOrUpdateAsync on entity with a default value causes InvalidOperationException
Given the following code:

**Entity**
```csharp
public class ExampleEntity
{
    public Guid Id { get; set; }
    public int Field { get; set; }
    public bool Other { get; set; }
}
```

**Entity fluent configuration**
```csharp
builder.Property(x => x.UserId).ValueGeneratedNever();
builder.Property(x => x.Field).IsRequired();
builder.Property(x => x.Other).IsRequired().HasDefaultValue(false);
```

**Example**
```csharp
await context.BulkInsertOrUpdateAsync(new List<ExampleEntity>
{
    new ExampleEntity
    {
        Id = Guid.NewGuid(),
        Field = 1,
        Other = False
    },
    new ExampleEntity
    {
        Id = Guid.NewGuid(),
        Field = 1,
        Other = False
    }
});
```

The exception occurs:

```
System.InvalidOperationException: The binary import operation was started with X column(s), but X value(s) were provided.
```

This happens because fields with a default value in the database are excluded from the insert statement https://github.com/borisdj/EFCore.BulkExtensions/blob/abe6ca5ed73634bca19f47f8335a736d4ca5d119/EFCore.BulkExtensions/SQLAdapters/PostgreSql/PostgreSqlAdapter.cs#L68

### PR DESCRIPTION
**Pull request by rwasef1830**
Make owned types (in same table) work in PostgreSQL.
Fix identity annotation identification. Fixes #795 and #695 and #770 and #566 and regression from #772. With passing unit test.

@borisdj

### CODE REVIEW

**Comment by rwasef1830** [comment]
I also discovered postgres integration doesn't properly implement "with graph" :-(

**Comment by borisdj** [comment]
Thx for PR, Great work.
Merged and v6.5.5 published. 

PS
Yes EF generated Sql is not always as expected, or as would a person write it directly.
Had similar issue before.
You can do first BulkInsert, then BulkRead.

**Comment by borisdj** [comment]
There was a bug, regarding Identity column, introduced a few days ago with PR for MySql support.
I only found it this morning, it's now fixed so take the sync with latest source.

**Comment by MWRouin** [comment]
Hello!

This did not work for me, i am trying to bulk insert  entities that has some owned properties (1 to 1 in same table) but they are being ignored and stored as null!

**Pull request merged**
