### PR TITLE
Async method enhancements

### PR DESCRIPTION
**Pull request by ysmoradi**
Added cancellation token support + Replaced non-async method calls with their async equivalent where possible + added ConfigureAwait(false) where missing.

### CODE REVIEW

**Comment by borisdj** [comment]
I think it it more practical to add cancellation token in BulkConfig, so signature of many methods would Not have to be changes in all those places.
Can you make that change to this commit.

**Comment by ysmoradi** [comment]
Good point, but some toolings such as ReSharper will advise developers to pass cancellation token if a method which is being called accepts that in its parameters directly.

**Comment by borisdj** [comment]
We don't have to obey ReSharper advise.
BulkConfilg already has several params that are later forwarded to SqlBulkCopy.

**Comment by ysmoradi** [comment]
Fair enough! ;D
Give me some time and I'll handle this.

**Comment by borisdj** [comment]
I've decided to go with passing Cancellation token.
Commit merged.

**Comment by ysmoradi** [comment]
Thanks in advance

**Pull request merged**
