### PR TITLE
Added ReplaceReadEntities property to BulkConfig (#571).

### PR DESCRIPTION
**Pull request by Systemko**
Hi!

Proposal for #571 'Return all existing entities from BulkRead'.

### CODE REVIEW

**Comment by borisdj** [comment]
Could you resolve the conflicts please.

**Comment by borisdj** [comment]
Can you resolve the conflicts.

**Comment by borisdj** [comment]
For some reason there are 65 files marked for change, you make take the latest source and make new clean commit with basic changes for this issue.

**Comment by Systemko** [comment]
I think it's total count of changed files throughout all commits since my first proposal. I have changed six files only. But it's ok, I'll make the clean one.

**Pull request merged**
