### PR TITLE
Update to EF Core 2.2

### LINKED ISSUE #121: Update to EF Core 2.2

### PR DESCRIPTION
**Pull request by ErikEJ**
fixes #121 

+ Improve test portability

### CODE REVIEW

**Comment by ErikEJ** [comment]
This is most likely not needed, as 2.2 is backwards compat

**Comment by borisdj** [comment]
Ok. I did plan eventually to update all used NuGet Dependencies to latest versions.
Guess no need to rush.

**Comment by ErikEJ** [comment]
I will test and report back

**Comment by mrTurkay** [comment]
same issue

**Pull request closed without merging**
