### PR TITLE
Split SQL Driver specific code into different adapters

### PR DESCRIPTION
**Pull request by popojargo**
I want to add support for PGSQL and before adding any new code, I'll like to extract the code specific to each SQL Driver into its own adapter. That way, it's more transparent in the BulkOperation file as we don't maintain a bunch of if for each driver

### CODE REVIEW

**Comment by borisdj** [comment]
I have merged some previous PullRequest, so can you first resolve current conflicts.
Thx for contrib.

**Comment by jigarbagadai** [comment]
@popojargo,

I am also looking for  PGSQL bulk extensions, let me know if you add or if i can contribute in those code.

**Review by ghodasarakartik — APPROVED** [review]

**Comment by popojargo** [comment]
@jigarbagadai I will resolve the conflicts and merge this pull request. I'm not using this library anymore so if it's too complicated, I'll let you do the PGSQL integration

**Comment by popojargo** [comment]
@borisdj  updated my pr

**Comment by borisdj** [comment]
Merged 👍

**Pull request merged**
