### PR TITLE
#466 Fix AmbiguousMatchException on update from 3.2.7 to 3.3.1 with EF core 5

### PR DESCRIPTION
**Pull request by JavidShoaei**
Fixes the issue with EF Core 5 AmbiguousMatchException.
#466

### CODE REVIEW

**Comment by JavidShoaei** [comment]
Fixes the issue with EF Core 5 `AmbiguousMatchException`.
#466

**Comment by borisdj** [comment]
There was a prior commit https://github.com/borisdj/EFCore.BulkExtensions/pull/475 for this fix:
`.GetMethod(nameof(DbContext.Set), new Type[] {});`

**Comment by JavidShoaei** [comment]
I think using `Array.Empty` instead of `new Type[]` is slightly better though.

**Comment by borisdj** [comment]
Changed.

**Pull request closed without merging**
