### PR TITLE
Only bulkInsert support for mySql

### PR DESCRIPTION
**Pull request by saeidbabaei-dev**
I have done BulkInsert method for mysql with out graph support.
please review my changes. if you agree with me, i will continue to support other bulk operations.
thank you in advance.

### CODE REVIEW

**Comment by borisdj** [comment]
Nice work.

**Comment by genaray** [comment]
Can you support SaveChanges for MySQL ? 
This is what i use primarly due to its easy useage ^^ Would be great

**Comment by saeidbabaei-dev** [comment]
Yes, i am going to support SaveChanges method for MySQL as soon as possible.

**Comment by EV0755** [comment]
Will you support  BatchUpdate for MySQL?

**Comment by borisdj** [comment]
BatchUpdate method will soon, in a few months as of EF7, be supported directly in EF Core, so no need for it here.
Probably both(Update/Delete) Batch ops will become deprecated as an Extension.

**Pull request merged**
